// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

/**
 * Protobuf type {@code AllPosts}
 */
public final class AllPosts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AllPosts)
    AllPostsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllPosts.newBuilder() to construct.
  private AllPosts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllPosts() {
    post_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AllPosts();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllPosts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              post_ = new java.util.ArrayList<via.sdj3.sep_t3.protobuf.PostReadGrpcDto>();
              mutable_bitField0_ |= 0x00000001;
            }
            post_.add(
                input.readMessage(via.sdj3.sep_t3.protobuf.PostReadGrpcDto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        post_ = java.util.Collections.unmodifiableList(post_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.sep_t3.protobuf.PostGrpcModel.internal_static_AllPosts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.sep_t3.protobuf.PostGrpcModel.internal_static_AllPosts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.sep_t3.protobuf.AllPosts.class, via.sdj3.sep_t3.protobuf.AllPosts.Builder.class);
  }

  public static final int POST_FIELD_NUMBER = 1;
  private java.util.List<via.sdj3.sep_t3.protobuf.PostReadGrpcDto> post_;
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.sep_t3.protobuf.PostReadGrpcDto> getPostList() {
    return post_;
  }
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder> 
      getPostOrBuilderList() {
    return post_;
  }
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  @java.lang.Override
  public int getPostCount() {
    return post_.size();
  }
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.sep_t3.protobuf.PostReadGrpcDto getPost(int index) {
    return post_.get(index);
  }
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder getPostOrBuilder(
      int index) {
    return post_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < post_.size(); i++) {
      output.writeMessage(1, post_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < post_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, post_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.sep_t3.protobuf.AllPosts)) {
      return super.equals(obj);
    }
    via.sdj3.sep_t3.protobuf.AllPosts other = (via.sdj3.sep_t3.protobuf.AllPosts) obj;

    if (!getPostList()
        .equals(other.getPostList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPostCount() > 0) {
      hash = (37 * hash) + POST_FIELD_NUMBER;
      hash = (53 * hash) + getPostList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.sep_t3.protobuf.AllPosts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.sep_t3.protobuf.AllPosts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AllPosts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AllPosts)
      via.sdj3.sep_t3.protobuf.AllPostsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.sep_t3.protobuf.PostGrpcModel.internal_static_AllPosts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.sep_t3.protobuf.PostGrpcModel.internal_static_AllPosts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.sep_t3.protobuf.AllPosts.class, via.sdj3.sep_t3.protobuf.AllPosts.Builder.class);
    }

    // Construct using via.sdj3.sep_t3.protobuf.AllPosts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPostFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (postBuilder_ == null) {
        post_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        postBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.sep_t3.protobuf.PostGrpcModel.internal_static_AllPosts_descriptor;
    }

    @java.lang.Override
    public via.sdj3.sep_t3.protobuf.AllPosts getDefaultInstanceForType() {
      return via.sdj3.sep_t3.protobuf.AllPosts.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.sep_t3.protobuf.AllPosts build() {
      via.sdj3.sep_t3.protobuf.AllPosts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.sep_t3.protobuf.AllPosts buildPartial() {
      via.sdj3.sep_t3.protobuf.AllPosts result = new via.sdj3.sep_t3.protobuf.AllPosts(this);
      int from_bitField0_ = bitField0_;
      if (postBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          post_ = java.util.Collections.unmodifiableList(post_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.post_ = post_;
      } else {
        result.post_ = postBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.sep_t3.protobuf.AllPosts) {
        return mergeFrom((via.sdj3.sep_t3.protobuf.AllPosts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.sep_t3.protobuf.AllPosts other) {
      if (other == via.sdj3.sep_t3.protobuf.AllPosts.getDefaultInstance()) return this;
      if (postBuilder_ == null) {
        if (!other.post_.isEmpty()) {
          if (post_.isEmpty()) {
            post_ = other.post_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePostIsMutable();
            post_.addAll(other.post_);
          }
          onChanged();
        }
      } else {
        if (!other.post_.isEmpty()) {
          if (postBuilder_.isEmpty()) {
            postBuilder_.dispose();
            postBuilder_ = null;
            post_ = other.post_;
            bitField0_ = (bitField0_ & ~0x00000001);
            postBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPostFieldBuilder() : null;
          } else {
            postBuilder_.addAllMessages(other.post_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.sep_t3.protobuf.AllPosts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.sep_t3.protobuf.AllPosts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sdj3.sep_t3.protobuf.PostReadGrpcDto> post_ =
      java.util.Collections.emptyList();
    private void ensurePostIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        post_ = new java.util.ArrayList<via.sdj3.sep_t3.protobuf.PostReadGrpcDto>(post_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.sep_t3.protobuf.PostReadGrpcDto, via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder, via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder> postBuilder_;

    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public java.util.List<via.sdj3.sep_t3.protobuf.PostReadGrpcDto> getPostList() {
      if (postBuilder_ == null) {
        return java.util.Collections.unmodifiableList(post_);
      } else {
        return postBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public int getPostCount() {
      if (postBuilder_ == null) {
        return post_.size();
      } else {
        return postBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.PostReadGrpcDto getPost(int index) {
      if (postBuilder_ == null) {
        return post_.get(index);
      } else {
        return postBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder setPost(
        int index, via.sdj3.sep_t3.protobuf.PostReadGrpcDto value) {
      if (postBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostIsMutable();
        post_.set(index, value);
        onChanged();
      } else {
        postBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder setPost(
        int index, via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder builderForValue) {
      if (postBuilder_ == null) {
        ensurePostIsMutable();
        post_.set(index, builderForValue.build());
        onChanged();
      } else {
        postBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder addPost(via.sdj3.sep_t3.protobuf.PostReadGrpcDto value) {
      if (postBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostIsMutable();
        post_.add(value);
        onChanged();
      } else {
        postBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder addPost(
        int index, via.sdj3.sep_t3.protobuf.PostReadGrpcDto value) {
      if (postBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePostIsMutable();
        post_.add(index, value);
        onChanged();
      } else {
        postBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder addPost(
        via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder builderForValue) {
      if (postBuilder_ == null) {
        ensurePostIsMutable();
        post_.add(builderForValue.build());
        onChanged();
      } else {
        postBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder addPost(
        int index, via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder builderForValue) {
      if (postBuilder_ == null) {
        ensurePostIsMutable();
        post_.add(index, builderForValue.build());
        onChanged();
      } else {
        postBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder addAllPost(
        java.lang.Iterable<? extends via.sdj3.sep_t3.protobuf.PostReadGrpcDto> values) {
      if (postBuilder_ == null) {
        ensurePostIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, post_);
        onChanged();
      } else {
        postBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder clearPost() {
      if (postBuilder_ == null) {
        post_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        postBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public Builder removePost(int index) {
      if (postBuilder_ == null) {
        ensurePostIsMutable();
        post_.remove(index);
        onChanged();
      } else {
        postBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder getPostBuilder(
        int index) {
      return getPostFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder getPostOrBuilder(
        int index) {
      if (postBuilder_ == null) {
        return post_.get(index);  } else {
        return postBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public java.util.List<? extends via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder> 
         getPostOrBuilderList() {
      if (postBuilder_ != null) {
        return postBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(post_);
      }
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder addPostBuilder() {
      return getPostFieldBuilder().addBuilder(
          via.sdj3.sep_t3.protobuf.PostReadGrpcDto.getDefaultInstance());
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder addPostBuilder(
        int index) {
      return getPostFieldBuilder().addBuilder(
          index, via.sdj3.sep_t3.protobuf.PostReadGrpcDto.getDefaultInstance());
    }
    /**
     * <code>repeated .PostReadGrpcDto post = 1;</code>
     */
    public java.util.List<via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder> 
         getPostBuilderList() {
      return getPostFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.sep_t3.protobuf.PostReadGrpcDto, via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder, via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder> 
        getPostFieldBuilder() {
      if (postBuilder_ == null) {
        postBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.sep_t3.protobuf.PostReadGrpcDto, via.sdj3.sep_t3.protobuf.PostReadGrpcDto.Builder, via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder>(
                post_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        post_ = null;
      }
      return postBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AllPosts)
  }

  // @@protoc_insertion_point(class_scope:AllPosts)
  private static final via.sdj3.sep_t3.protobuf.AllPosts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.sep_t3.protobuf.AllPosts();
  }

  public static via.sdj3.sep_t3.protobuf.AllPosts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllPosts>
      PARSER = new com.google.protobuf.AbstractParser<AllPosts>() {
    @java.lang.Override
    public AllPosts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllPosts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllPosts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllPosts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.sep_t3.protobuf.AllPosts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

