// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public interface AllPostsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllPosts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  java.util.List<via.sdj3.sep_t3.protobuf.PostReadGrpcDto> 
      getPostList();
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  via.sdj3.sep_t3.protobuf.PostReadGrpcDto getPost(int index);
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  int getPostCount();
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  java.util.List<? extends via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder> 
      getPostOrBuilderList();
  /**
   * <code>repeated .PostReadGrpcDto post = 1;</code>
   */
  via.sdj3.sep_t3.protobuf.PostReadGrpcDtoOrBuilder getPostOrBuilder(
      int index);
}
