// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

/**
 * Protobuf type {@code AllUsers}
 */
public final class AllUsers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AllUsers)
    AllUsersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllUsers.newBuilder() to construct.
  private AllUsers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllUsers() {
    users_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AllUsers();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllUsers(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              users_ = new java.util.ArrayList<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            users_.add(
                input.readMessage(via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        users_ = java.util.Collections.unmodifiableList(users_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.sep_t3.protobuf.UserGrpcModel.internal_static_AllUsers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.sep_t3.protobuf.UserGrpcModel.internal_static_AllUsers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.sep_t3.protobuf.AllUsers.class, via.sdj3.sep_t3.protobuf.AllUsers.Builder.class);
  }

  public static final int USERS_FIELD_NUMBER = 1;
  private java.util.List<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO> users_;
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.sep_t3.protobuf.UserReadGrpcDTO getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  @java.lang.Override
  public via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(1, users_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < users_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, users_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.sep_t3.protobuf.AllUsers)) {
      return super.equals(obj);
    }
    via.sdj3.sep_t3.protobuf.AllUsers other = (via.sdj3.sep_t3.protobuf.AllUsers) obj;

    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.sep_t3.protobuf.AllUsers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.sep_t3.protobuf.AllUsers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AllUsers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AllUsers)
      via.sdj3.sep_t3.protobuf.AllUsersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.sep_t3.protobuf.UserGrpcModel.internal_static_AllUsers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.sep_t3.protobuf.UserGrpcModel.internal_static_AllUsers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.sep_t3.protobuf.AllUsers.class, via.sdj3.sep_t3.protobuf.AllUsers.Builder.class);
    }

    // Construct using via.sdj3.sep_t3.protobuf.AllUsers.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUsersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        usersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.sep_t3.protobuf.UserGrpcModel.internal_static_AllUsers_descriptor;
    }

    @java.lang.Override
    public via.sdj3.sep_t3.protobuf.AllUsers getDefaultInstanceForType() {
      return via.sdj3.sep_t3.protobuf.AllUsers.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.sep_t3.protobuf.AllUsers build() {
      via.sdj3.sep_t3.protobuf.AllUsers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.sep_t3.protobuf.AllUsers buildPartial() {
      via.sdj3.sep_t3.protobuf.AllUsers result = new via.sdj3.sep_t3.protobuf.AllUsers(this);
      int from_bitField0_ = bitField0_;
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.sep_t3.protobuf.AllUsers) {
        return mergeFrom((via.sdj3.sep_t3.protobuf.AllUsers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.sep_t3.protobuf.AllUsers other) {
      if (other == via.sdj3.sep_t3.protobuf.AllUsers.getDefaultInstance()) return this;
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000001);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.sep_t3.protobuf.AllUsers parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.sep_t3.protobuf.AllUsers) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        users_ = new java.util.ArrayList<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO>(users_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.sep_t3.protobuf.UserReadGrpcDTO, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder, via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder> usersBuilder_;

    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public java.util.List<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.UserReadGrpcDTO getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder setUsers(
        int index, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder setUsers(
        int index, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder addUsers(via.sdj3.sep_t3.protobuf.UserReadGrpcDTO value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder addUsers(
        int index, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder addUsers(
        via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder addUsers(
        int index, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends via.sdj3.sep_t3.protobuf.UserReadGrpcDTO> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder getUsersBuilder(
        int index) {
      return getUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public java.util.List<? extends via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder addUsersBuilder() {
      return getUsersFieldBuilder().addBuilder(
          via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder addUsersBuilder(
        int index) {
      return getUsersFieldBuilder().addBuilder(
          index, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .UserReadGrpcDTO users = 1;</code>
     */
    public java.util.List<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder> 
         getUsersBuilderList() {
      return getUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.sep_t3.protobuf.UserReadGrpcDTO, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder, via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder> 
        getUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.sep_t3.protobuf.UserReadGrpcDTO, via.sdj3.sep_t3.protobuf.UserReadGrpcDTO.Builder, via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder>(
                users_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AllUsers)
  }

  // @@protoc_insertion_point(class_scope:AllUsers)
  private static final via.sdj3.sep_t3.protobuf.AllUsers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.sep_t3.protobuf.AllUsers();
  }

  public static via.sdj3.sep_t3.protobuf.AllUsers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllUsers>
      PARSER = new com.google.protobuf.AbstractParser<AllUsers>() {
    @java.lang.Override
    public AllUsers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllUsers(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllUsers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllUsers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.sep_t3.protobuf.AllUsers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

