// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public interface AllUsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllUsers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  java.util.List<via.sdj3.sep_t3.protobuf.UserReadGrpcDTO> 
      getUsersList();
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  via.sdj3.sep_t3.protobuf.UserReadGrpcDTO getUsers(int index);
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  java.util.List<? extends via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .UserReadGrpcDTO users = 1;</code>
   */
  via.sdj3.sep_t3.protobuf.UserReadGrpcDTOOrBuilder getUsersOrBuilder(
      int index);
}
