// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package via.sdj3.sep_t3.protobuf;

public interface GenericMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenericMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
