// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public interface PostCreationGrpcDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostCreationGrpcDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string description = 1;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 1;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string location = 2;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 categories = 3;</code>
   * @return The categories.
   */
  int getCategories();

  /**
   * <code>int32 sellerId = 4;</code>
   * @return The sellerId.
   */
  int getSellerId();

  /**
   * <code>string picture = 5;</code>
   * @return The picture.
   */
  java.lang.String getPicture();
  /**
   * <code>string picture = 5;</code>
   * @return The bytes for picture.
   */
  com.google.protobuf.ByteString
      getPictureBytes();

  /**
   * <code>int32 price = 6;</code>
   * @return The price.
   */
  int getPrice();
}
