// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public final class PostGrpcModel {
  private PostGrpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostCreationGrpcDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostCreationGrpcDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostReadGrpcDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostReadGrpcDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllPosts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllPosts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PostGrpcModel.proto\032\014common.proto\"\202\001\n\023" +
      "PostCreationGrpcDto\022\023\n\013description\030\001 \001(\t" +
      "\022\020\n\010location\030\002 \001(\t\022\022\n\ncategories\030\003 \001(\005\022\020" +
      "\n\010sellerId\030\004 \001(\005\022\017\n\007picture\030\005 \001(\t\022\r\n\005pri" +
      "ce\030\006 \001(\005\"\240\001\n\017PostReadGrpcDto\022\n\n\002id\030\001 \001(\005" +
      "\022\024\n\014creationDate\030\002 \001(\005\022\023\n\013description\030\003 " +
      "\001(\t\022\020\n\010location\030\004 \001(\t\022\022\n\ncategories\030\005 \001(" +
      "\005\022\020\n\010sellerId\030\006 \001(\005\022\017\n\007picture\030\007 \001(\t\022\r\n\005" +
      "price\030\010 \001(\005\"*\n\010AllPosts\022\036\n\004post\030\001 \003(\0132\020." +
      "PostReadGrpcDto2\227\001\n\013postService\022 \n\013getAl" +
      "lPosts\022\006.Empty\032\t.AllPosts\0224\n\ncreatePost\022" +
      "\024.PostCreationGrpcDto\032\020.PostReadGrpcDto\022" +
      "0\n\013getPostById\022\017.GenericMessage\032\020.PostRe" +
      "adGrpcDtoB\034\n\030via.sdj3.sep_t3.protobufP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sdj3.sep_t3.protobuf.Common.getDescriptor(),
        });
    internal_static_PostCreationGrpcDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PostCreationGrpcDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostCreationGrpcDto_descriptor,
        new java.lang.String[] { "Description", "Location", "Categories", "SellerId", "Picture", "Price", });
    internal_static_PostReadGrpcDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PostReadGrpcDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostReadGrpcDto_descriptor,
        new java.lang.String[] { "Id", "CreationDate", "Description", "Location", "Categories", "SellerId", "Picture", "Price", });
    internal_static_AllPosts_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AllPosts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllPosts_descriptor,
        new java.lang.String[] { "Post", });
    via.sdj3.sep_t3.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
