// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public interface PostReadGrpcDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PostReadGrpcDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 creationDate = 2;</code>
   * @return The creationDate.
   */
  int getCreationDate();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string location = 4;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 4;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string categories = 5;</code>
   * @return The categories.
   */
  java.lang.String getCategories();
  /**
   * <code>string categories = 5;</code>
   * @return The bytes for categories.
   */
  com.google.protobuf.ByteString
      getCategoriesBytes();

  /**
   * <code>int32 sellerId = 6;</code>
   * @return The sellerId.
   */
  int getSellerId();

  /**
   * <code>string picture = 7;</code>
   * @return The picture.
   */
  java.lang.String getPicture();
  /**
   * <code>string picture = 7;</code>
   * @return The bytes for picture.
   */
  com.google.protobuf.ByteString
      getPictureBytes();

  /**
   * <code>int32 price = 8;</code>
   * @return The price.
   */
  int getPrice();
}
