// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public interface UserReadGrpcDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserReadGrpcDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string role = 3;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 3;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string fullName = 4;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 4;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string email = 5;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phoneNumber = 6;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 6;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string address = 7;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 7;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 rating = 8;</code>
   * @return The rating.
   */
  int getRating();

  /**
   * <code>int32 registrationDate = 9;</code>
   * @return The registrationDate.
   */
  int getRegistrationDate();

  /**
   * <code>int32 lastSeenDate = 10;</code>
   * @return The lastSeenDate.
   */
  int getLastSeenDate();
}
