// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP3.proto

package via.sdj3.sep_t3.protobuf;

public interface UsersGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsersGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .User users = 1;</code>
   */
  java.util.List<via.sdj3.sep_t3.protobuf.User> 
      getUsersList();
  /**
   * <code>repeated .User users = 1;</code>
   */
  via.sdj3.sep_t3.protobuf.User getUsers(int index);
  /**
   * <code>repeated .User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .User users = 1;</code>
   */
  java.util.List<? extends via.sdj3.sep_t3.protobuf.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .User users = 1;</code>
   */
  via.sdj3.sep_t3.protobuf.UserOrBuilder getUsersOrBuilder(
      int index);
}
