// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserGrpcModel.proto

package via.sdj3.sep_t3.protobuf;

public final class UserGrpcModel {
  private UserGrpcModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserCreationGrpcDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserCreationGrpcDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserReadGrpcDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserReadGrpcDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AllUsers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AllUsers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginCredentials_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginCredentials_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023UserGrpcModel.proto\032\014common.proto\"\212\001\n\023" +
      "UserCreationGrpcDto\022\020\n\010username\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t\022\014\n\004role\030\003 \001(\t\022\r\n\005email\030\004" +
      " \001(\t\022\014\n\004name\030\005 \001(\t\022\017\n\007address\030\006 \001(\t\022\023\n\013p" +
      "honeNumber\030\007 \001(\t\"\300\001\n\017UserReadGrpcDTO\022\n\n\002" +
      "id\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\014\n\004role\030\003 \001(\t" +
      "\022\014\n\004name\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\022\023\n\013phoneNu" +
      "mber\030\006 \001(\t\022\017\n\007address\030\007 \001(\t\022\016\n\006rating\030\010 " +
      "\001(\005\022\030\n\020registrationDate\030\t \001(\005\022\024\n\014lastSee" +
      "nDate\030\n \001(\005\"+\n\010AllUsers\022\037\n\005users\030\001 \003(\0132\020" +
      ".UserReadGrpcDTO\"6\n\020LoginCredentials\022\020\n\010" +
      "username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t2\374\001\n\nsep" +
      "Service\022 \n\013getAllUsers\022\006.Empty\032\t.AllUser" +
      "s\0224\n\ncreateUser\022\024.UserCreationGrpcDto\032\020." +
      "UserReadGrpcDTO\0220\n\013getUserById\022\017.Generic" +
      "Message\032\020.UserReadGrpcDTO\0224\n\rvalidateLog" +
      "in\022\021.LoginCredentials\032\020.UserReadGrpcDTO\022" +
      ".\n\ndeleteById\022\017.GenericMessage\032\017.Generic" +
      "MessageB\034\n\030via.sdj3.sep_t3.protobufP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sdj3.sep_t3.protobuf.Common.getDescriptor(),
        });
    internal_static_UserCreationGrpcDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserCreationGrpcDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserCreationGrpcDto_descriptor,
        new java.lang.String[] { "Username", "Password", "Role", "Email", "Name", "Address", "PhoneNumber", });
    internal_static_UserReadGrpcDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserReadGrpcDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserReadGrpcDTO_descriptor,
        new java.lang.String[] { "Id", "Username", "Role", "Name", "Email", "PhoneNumber", "Address", "Rating", "RegistrationDate", "LastSeenDate", });
    internal_static_AllUsers_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AllUsers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AllUsers_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_LoginCredentials_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LoginCredentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginCredentials_descriptor,
        new java.lang.String[] { "Username", "Password", });
    via.sdj3.sep_t3.protobuf.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
